version: "3.4"
services:
  server:
    image: gocd/gocd-server:v21.2.0
    restart: always
    ports:
      - "8153:8153"

  agent:
    image: gocd/gocd-agent-ubuntu-18.04:v21.2.0
    restart: always
    environment:
      - GO_SERVER_URL=http://server:8153/go
      - AGENT_AUTO_REGISTER_KEY=agent-autoregister-key

    deploy:
      replicas: 2

    depends_on:
      - "server"
